###############################################
# 다이어그램 관련 API 테스트
###############################################

@baseUrl = http://localhost:8000
@projectId = project-123
@apiId = api-456

### 프롬프트 채팅 요청 테스트
POST {{baseUrl}}/api/v1/projects/{{projectId}}/apis/{{apiId}}/chats
Content-Type: application/json

{
  "tag": "REFACTORING",
  "promptType": "BODY",
  "message": "선택한 메서드를 리팩토링 해주세요",
  "targetMethods": [
    {
      "methodId": "fd93c6bd-b2b6-4d06-86a4-ce027da3bb85"
    }
  ]
}

> {%
    client.global.set("streamId", response.body.streamId);
%}

### SSE 연결 테스트 (브라우저에서 테스트하는 것이 좋음)
GET {{baseUrl}}/api/v1/sse/connect/{{streamId}}

### SSE 연결 테스트 (브라우저에서 테스트하는 것이 좋음)
GET {{baseUrl}}/api/v1/sse/stream/{{streamId}}

###
GET {{baseUrl}}/api/v1/projects/{{projectId}}/apis/{{apiId}}/chats