spring:
  application:
    name: backend

  ### problem details
  mvc:
    problemdetails:
      enabled: true

  ### Google OAuth ###
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${REDIRECT_URI}/oauth2/code/google
            scope:
              - profile
              - email

  config:
    import:
      - optional:file:.env[.properties]

  jackson:
    time-zone: Asia/Seoul

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: ${JPA_SHOW_SQL}
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: "SELECT 1"
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiretime: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}

oauth2:
  redirectUri: ${REDIRECT_URI}
  frontRedirectUri: ${FRONT_REDIRECT_URI}
