openapi: 3.0.0

info:
  title: 메서드 도식화 API
  description: 메서드 도식화에 관련된 API 명세
  version: 1.0.0
  contact:
    name: API 지원팀
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: 개발 서버
  - url: http://localhost:8081
    description: 개발용 목 서버
  - url: https://scrud.co.kr
    description: 운영 서버

tags:
  - name: Component
    description: 컴포넌트 메서드, 클래스와 관련된 메서드
  - name: ScrudApi
    description: API 상태 수정 API
  - name: Canvas
    description: 도식화와 관련된 메서드
  - name: Chat
    description: 프롬프트 채팅 관련 API

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT 인증 토큰을 사용합니다. 예: Bearer {token}"

paths:
  /api/v1/projects/{projectId}/apis/{apiId}/chats:
    get:
      tags:
        - Chat
      summary: 프롬프트 채팅 기록 조회
      description: 특정 API에 대한 프롬프트 채팅 기록을 시간순으로 조회합니다.
      operationId: getPrompts
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/GetPromptsResponse"
        '404':
          $ref: './components/responses/exception-response.yaml#/NotFoundException'
    post:
      tags:
        - Chat
      summary: SSE 기반프롬프트 채팅 요청
      description: |
        프롬프트를 입력하여 도식화 수정을 요청하거나 설명을 요청합니다. 응답 값으로 SSE Id를 받습니다.
        Id 값을 /api/sse/connect/{SSEId} API에 입력하여 값을 얻을 수 있습니다.
      operationId: promptChat
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/UserChatRequest'
            examples:
              "예시1":
                $ref: './components/examples/canvas-example.yaml#/UserChatRequestExample'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/PromptChatResponse"
        '404':
          $ref: "./components/responses/exception-response.yaml#/NotFoundException"
  /api/sse/connect/{SSEId}:
    get:
      tags:
        - Chat
      operationId: connectSSE
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/SSEId'
      security:
        - bearerAuth: [ ]
      summary: 'SSE 연결을 설정합니다.'
      description: '서버와 클라이언트 간의 SSE 연결을 설정하여 실시간 이벤트 스트림을 수신할 수 있습니다.'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/ConnectSSEResponse"
        '401':
          description: '인증되지 않은 요청'
  /api/v1/projects/{projectId}/apis/{apiId}/components/{componentId}/position:
    put:
      tags:
        - Component
      operationId: updateComponentPosition
      summary: '컴포넌트의 위치를 업데이트합니다.'
      description: '도식화에서 특정 컴포넌트의 위치 좌표를 변경합니다.'
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
        - $ref: './components/schemas/canvas-schema.yaml#/ComponentId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/ComponentPositionUpdateRequest'
            examples:
              example1:
                $ref: './components/examples/canvas-example.yaml#/ComponentPositionUpdateRequestExample'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/UpdateComponentPositionResponse"
        '404':
          $ref: "./components/responses/exception-response.yaml#/NotFoundException"
  /api/v1/projects/{projectId}/apis:
    get:
      tags:
        - ScrudApi
      operationId: searchApiStatus
      summary: 'API 상태(USER_COMPLETED, AI_GENERATED 등)에 대해 검색합니다.'
      description: |
        parameter에 API의 상태(AI_GENERATED 등) 을 검색할 수 있습니다. 
        수정된 날자순으로 정렬되어 출력됩니다.
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/Include'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/SearchApiStatusResponse"
  /api/v1/projects/{projectId}/apis/{apiId}/versions/{versionId}:
    get:
      tags:
        - Canvas
      summary: 특정 버전의 도식화 데이터 조회
      description: 특정 프로젝트의 특정 API 버전에 대한 메서드 도식화 데이터를 가져옵니다.
      operationId: getDiagram
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
        - $ref: './components/schemas/canvas-schema.yaml#/VersionId'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/GetDiagramResponse"
        '404':
          $ref: './components/responses/exception-response.yaml#/NotFoundException'
  /api/v1/projects/{projectId}/apis/{apiId}/status:
    put:
      tags:
        - ScrudApi
      operationId: changeApiProcessStatus
      summary: API 처리 상태를 변경합니다.
      description: API 처리 상태를 변경합니다.
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      requestBody:
        required: true
        description: 처리상태
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/ApiProcessStateRequest'
            examples:
              example1:
                $ref: './components/examples/canvas-example.yaml#/ApiProcessStateRequestExample'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/ChangeApiProcessStatusResponse"
  /api/v1/projects/{projectId}/apis/{apiId}/diagrams:
    post:
      tags:
        - Canvas
      operationId: createDiagram
      summary: API를 최초로 도식화 할 때 사용합니다.
      description: 도식화를 처음 실행할 때 사용하는 API 입니다.
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      responses:
        '200':
          $ref: "./components/responses/canvas-response.yaml#/GetDiagramResponse"




