openapi: 3.0.0

info:
  title: 메서드 도식화 API
  description: 메서드 도식화에 관련된 API 명세
  version: 1.0.0
  contact:
    name: API 지원팀
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: 개발 서버
  - url: https://scrud.co.kr
    description: 운영 서버

tags:
  - name: Component
    description: 컴포넌트 메서드, 클래스와 관련된 메서드
  - name: ScrudApi
    description: API 상태 수정 API
  - name: Canvas
    description: 도식화와 관련된 메서드
  - name: Chat
    description: 프롬프트 채팅 관련 API


paths:
  /api/sse/send:
    post:
      tags:
        - Chat
      deprecated: true
      operationId: sendSSEEvent
      summary: 'SSE 이벤트를 전송받습니다.'
      description: '연결된 특정 클라이언트 또는 모든 클라이언트에게 이벤트를 전송합니다.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/SSEEventDto'
      responses:
        '200':
          description: '이벤트 전송 성공'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  sentCount:
                    type: integer
                    description: '이벤트가 전송된 클라이언트 수'
                  message:
                    type: string
        '400':
          description: '잘못된 요청'
        '401':
          description: '인증되지 않은 요청'
      security:
        - bearerAuth: [ ]
  /api/sse/connect:
    get:
      tags:
        - Chat
      operationId: connectSSE
      deprecated: true
      summary: 'SSE 연결을 설정합니다.'
      description: '서버와 클라이언트 간의 SSE 연결을 설정하여 실시간 이벤트 스트림을 수신할 수 있습니다.'
      responses:
        '200':
          description: 'SSE 연결 성공'
          content:
            text/event-stream:
              schema:
                type: string
                description: '이벤트 스트림'
        '401':
          description: '인증되지 않은 요청'
        '429':
          description: '너무 많은 요청'
      security:
        - bearerAuth: [ ]
  /api/v1/projects/{projectId}/apis/{apiId}/components/{componentId}/position:
    put:
      tags:
        - Component
      operationId: updateComponentPosition
      summary: '컴포넌트의 위치를 업데이트합니다.'
      description: '도식화에서 특정 컴포넌트의 위치 좌표를 변경합니다.'
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
        - $ref: './components/schemas/canvas-schema.yaml#/ComponentId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/ComponentPositionUpdateRequest'
      responses:
        '200':
          description: '컴포넌트 위치 업데이트 성공'
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/ComponentUpdatedResponse'
        '404':
          description: '컴포넌트를 찾을 수 없음'
          content:
            application/json:
              schema:
                $ref: './components/responses/exception-response.yaml#/NotFoundException'
  /api/v1/projects/{projectId}/apis:
    get:
      tags:
        - ScrudApi
      operationId: getIncompleteApis
      summary: '완료되지 않은 API 목록을 조회합니다.'
      description: |
        현재 USER_COMPLETED 상태가 아닌(AI_GENERATED 또는 AI_VISUALIZED) 모든 API 목록을 조회합니다. 수정된 날자순으로 정렬되어 출력됩니다.

      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/Incomplete'
      responses:
        '200':
          description: '미완료 API 목록 조회 성공'
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/ApiSummaryPageResponse'
  /api/v1/projects/{projectId}/apis/{apiId}/versions/{versionId}:
    get:
      tags:
        - Canvas
      summary: 특정 버전의 도식화 데이터 조회
      description: 특정 프로젝트의 특정 API 버전에 대한 메서드 도식화 데이터를 가져옵니다.
      operationId: getDiagram
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
        - $ref: './components/schemas/canvas-schema.yaml#/VersionId'
      responses:
        '200':
          description: 성공적으로 도식화 데이터를 조회함
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/DiagramModelDto'
        '404':
          $ref: './components/responses/exception-response.yaml#/NotFoundException'
  /api/v1/projects/{projectId}/apis/{apiId}/status:
    put:
      tags:
        - ScrudApi
      operationId: changeApiProcessStatus
      summary: API 처리 상태를 변경합니다.
      description: API 처리 상태를 변경합니다.
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      requestBody:
        required: true
        description: 처리상태
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/ApiProcessStateRequest'
      responses:
        '200':
          description: 프롬프트 처리 결과
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/ApiProcessStateUpdatedResponse'
  /api/v1/projects/{projectId}/apis/{apiId}/chats:
    get:
      tags:
        - Chat
      summary: 프롬프트 채팅 기록 조회
      description: 특정 API에 대한 프롬프트 채팅 기록을 시간순으로 조회합니다.
      operationId: getPrompts
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      responses:
        '200':
          description: 프롬프트 채팅 기록 조회 결과
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/ChatHistoryResponse'
        '404':
          $ref: './components/responses/exception-response.yaml#/NotFoundException'

    post:
      tags:
        - Chat
      summary: 프롬프트 채팅 요청
      description: 프롬프트를 입력하여 도식화 수정을 요청하거나 설명을 요청합니다.
      operationId: promptChat
      parameters:
        - $ref: './components/schemas/canvas-schema.yaml#/ProjectId'
        - $ref: './components/schemas/canvas-schema.yaml#/ApiId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/canvas-schema.yaml#/UserChatRequest'
      responses:
        '200':
          description: 프롬프트 처리 결과
          content:
            application/json:
              schema:
                $ref: './components/schemas/canvas-schema.yaml#/SystemChatResponse'
        '404':
          $ref: './components/responses/exception-response.yaml#/NotFoundException'
