openapi: 3.0.3
info:
  title: 게시판 API
  version: 1.0.0
  description: 게시판 기능 관련 API 명세입니다.
  contact:
    name: API 지원팀
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: 개발 서버
  - url: https://board.example.com
    description: 운영 서버

tags:
  - name: Comment
    description: 댓글 관련 API

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT 인증 토큰 사용 (예: Bearer {token})"

paths:
  /api/v1/posts/{postId}/comments:
    post:
      tags: [Comment]
      summary: 댓글 작성
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      requestBody:
        $ref: './components/requests/comment-request.yaml#/CreateCommentRequest'
      responses:
        '201':
          $ref: './components/responses/success-response.yaml#/SuccessCreated'

    get:
      tags: [Comment]
      summary: 댓글 조회
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      responses:
        '200':
          $ref: './components/responses/comment-response.yaml#/GetCommentListResponse'

  /api/v1/comments/{commentId}:
    patch:
      tags: [Comment]
      summary: 댓글 수정
      parameters:
        - $ref: './components/schemas/comment-schema.yaml#/CommentId'
      requestBody:
        $ref: './components/schemas/comment-schema.yaml#/UpdateCommentRequest'
      responses:
        '200':
          $ref: './components/responses/success-response.yaml#/SuccessNoContent'

    delete:
      tags: [Comment]
      summary: 댓글 삭제
      parameters:
        - $ref: './components/schemas/comment-schema.yaml#/CommentId'
      responses:
        '204':
          $ref: './components/responses/success-response.yaml#/SuccessNoContent'

  /api/v1/comments/{commentId}/vote:
    post:
      tags: [Comment]
      summary: 댓글 추천/비추천
      parameters:
        - $ref: './components/schemas/comment-schema.yaml#/CommentId'
      requestBody:
        $ref: './components/schemas/comment-schema.yaml#/CommentVoteRequest'
      responses:
        '200':
          $ref: './components/responses/comment-response.yaml#/VoteCommentResponse'
