openapi: 3.0.0
info:
  title: 게시판 API
  version: 1.0.0
  description: 게시판 기능 관련 API 명세입니다.
  contact:
    name: API 지원팀
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: 개발 서버
  - url: http://localhost:8081
    description: 개발용 목 서버
  - url: https://scrud.co.kr
    description: 운영 서버

tags:
  - name: Post
    description: 게시글 관련 API

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT 인증 토큰 사용 (예: Bearer {token})"

paths:
  /api/v1/posts:
    post:
      tags: [ Post ]
      summary: 게시글 작성
      operationId: createPost
      requestBody:
        $ref: './components/requests/post-request.yaml#/CreatePostRequest'
      responses:
        '201':
          $ref: './components/responses/post-response.yaml#/CreatePostResponse'

    get:
      tags: [ Post ]
      summary: 게시글 목록 조회
      operationId: getPostList
      parameters:
        - $ref: './components/schemas/page-schema.yaml#/Page'
        - $ref: './components/schemas/page-schema.yaml#/Size'
        - $ref: './components/schemas/page-schema.yaml#/PostSort'
        - $ref: './components/schemas/page-schema.yaml#/PostOrder'
        - $ref: './components/requests/post-request.yaml#/SearchPostParam'
        - $ref: './components/requests/post-request.yaml#/SearchTypeParam'
        - $ref: './components/requests/post-request.yaml#/CategoryIdParam'
      responses:
        '200':
          $ref: './components/responses/post-response.yaml#/GetPostListResponse'

  /api/v1/posts/{postId}:
    get:
      tags: [ Post ]
      summary: 게시글 상세 조회
      operationId: getPostById
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      responses:
        '200':
          $ref: './components/responses/post-response.yaml#/GetPostDetailResponse'

    put:
      tags: [ Post ]
      summary: 게시글 수정
      operationId: updatePost
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      requestBody:
        $ref: './components/requests/post-request.yaml#/UpdatePostRequest'
      responses:
        '200':
          $ref: './components/responses/success-response.yaml#/SuccessNoContent'

    delete:
      tags: [ Post ]
      summary: 게시글 삭제
      operationId: deletePost
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      responses:
        '204':
          $ref: './components/responses/success-response.yaml#/SuccessNoContent'

  /api/v1/posts/{postId}/vote:
    post:
      tags: [ Post ]
      summary: 게시글 추천/비추천
      operationId: votePost
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      requestBody:
        $ref: './components/requests/post-request.yaml#/PostVoteRequest'
      responses:
        '200':
          $ref: './components/responses/post-response.yaml#/VotePostResponse'

  /api/v1/posts/{postId}/status:
    patch:
      tags: [ Post ]
      summary: 게시글 상태 변경
      operationId: updatePostStatus
      parameters:
        - $ref: './components/schemas/post-schema.yaml#/PostId'
      requestBody:
        $ref: './components/requests/post-request.yaml#/UpdatePostStatusRequest'
      responses:
        '200':
          $ref: './components/responses/success-response.yaml#/SuccessNoContent'